### ISSUE TITLE
It just won't open

### ISSUE THREAD

**Issue by Mdk1337** [fiftythreecorp/LeagueOfLegendsAccountChecker#11]
All of a sudden it stopped working, trying with a fresh .exe, it just won't start (it can be seen in task manager but instantly stops working). Is it just me or this app's dead?

**Comment by anon88391** [comment]
Experiencing the same issue here.

**Comment by pajicadvance** [comment]
Same issue, tried downloading a fresh install, won't open

**Comment by fiftythreecorp** [comment]
I know about the problem, I will try to fix it soon. 

Thanks!

**Comment by SaltyHampster** [comment]
Still has the same issue even with newest update 1.04

**Comment by Mdk1337** [comment]
> I know about the problem, I will try to fix it soon.
> 
> Thanks!
It's working now, thanks for fixing the issue :)
