### ISSUE TITLE
workers

### ISSUE THREAD

**Issue by apektos1000** [fiftythreecorp/LeagueOfLegendsAccountChecker#5]
why only 15 max workers?
can you make it faster please?
what about 250 or 500 workers?
btw please make more options for saving hits because when i want to save the hits i have to write every account by my self (because there is no save option in .txt)

**Comment by kneegrowz** [comment]
klapse re

**Comment by fiftythreecorp** [comment]
With more workers there are crashes, I will try to fix it in the next update.
